title: SoBIG
tagline: Solav Biomechanical Interfaces Group
description: >
  SoBIG is a research group at Technion studying human musculoskeletal
  biomechanics and developing innovative medical devices for prosthetic
  and orthotic users.
url: "https://www.solavlab.com"
baseurl: ""

email: sobig@technion.ac.il
phone: "+972-73-378-5494"
address: "103 Lady Davis Bldg., Technion City, Haifa 3200003, Israel"
maps_link: "https://goo.gl/maps/yNZnYossAYzP5axc7"

social:
  linkedin: "https://www.linkedin.com/in/dana-solav-31878b41/"
  scholar: "https://scholar.google.com/citations?user=AwjDDLAAAAAJ&hl=en&oi=ao"
  orcid: "https://orcid.org/0000-0003-3215-0401"
  github: "https://github.com/SolavLab"

# Build settings
markdown: kramdown
permalink: /:title/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-feed

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - "*.zip"
  - README.md
